[target.wasm32-unknown-unknown]
# export CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER=wasm-server-runner
# cargo run --target wasm32-unknown-unknown
runner = "wasm-server-runner"
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[alias]
# disable dynamic linking for the moment as it is not supported with jpeg features
# https://github.com/bevyengine/bevy/issues/14117
#bd = "build --features bevy/dynamic_linking"
bd = "build"
br = "build -r"
bwd = "build --target wasm32-unknown-unknown"
bwr = "build --profile wasm-release --target wasm32-unknown-unknown"
#rd = "run --features bevy/dynamic_linking"
rd = "run"
rr = "run -r"
rwd = "run --target wasm32-unknown-unknown"
rwr = "run --profile wasm-release --target wasm32-unknown-unknown"
